name: DevFest URL Request
description: Request to add or update a DevFest URL
title: "Update DevFest details: [City] (slug: [slug])"
labels: ["update-url"]
body:
  - type: markdown
    attributes:
      value: |
        **Important**: In the title above, do not change the city or slug.
        
        Thanks for taking the time to request a DevFest URL!
        Please fill out the information below to help us process your request quickly.
  
  - type: input
    id: destination-url
    attributes:
      label: Destination URL *
      description: The URL that users should be redirected to (must be a valid HTTPS URL)
      placeholder: https://gdg.community.dev/gdg-bangalore/
    validations:
      required: true
      pattern: ^https:\/\/.*
  
  - type: input
    id: devfest-date
    attributes:
      label: DevFest Date *
      description: The date of the DevFest event (YYYY-MM-DD format)
      placeholder: "2024-10-12"
    validations:
      required: true
      pattern: ^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$
  
  - type: input
    id: devfest-name
    attributes:
      label: DevFest Name
      description: The full name of the DevFest event (e.g., DevFest Bangalore 2024)
      placeholder: DevFest Bangalore 2024
    validations:
      required: false
  
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: The information provided is accurate and up-to-date
          required: true 